apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80  # Service port to expose (default HTTP)
    targetPort: 80  # Maps to container port
  type: ClusterIP  # Service accessible only within the cluster

---
apiVersion: v1
kind: Service
metadata:
    name: app-two
spec:
    selector:
        app: app-two
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    # type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
    name: app-three
spec:
    selector:
        app: app-three
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    # type: ClusterIP
