BOX_IMAGE = "hashicorp/bionic64"
VM_PROVIDER = "virtualbox"

# Server
SERVER_NAME = "cmariotS"
SERVER_IP = "192.168.56.110"


Vagrant.configure("2") do |config|

    # Virtual machine provider settings
    config.vm.provider VM_PROVIDER do |vm_provider|
        vm_provider.cpus = 2
        vm_provider.memory = "1024"
    end

    # Define the first VM: Server
    config.vm.define SERVER_NAME do |server|
        server.vm.box = BOX_IMAGE
        server.vm.hostname = SERVER_NAME
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.provision "shell", path: "scripts/server.sh"
    end

end
