Vagrant.configure("2") do |config|

    # Define the first VM: Server
    config.vm.define "wloS" do |server|
        server.vm.box = "bento/ubuntu-24.04"
        server.vm.hostname = "wloS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.cpus = 1
            vb.memory = "1024"
            # vb.gui = true
        end
        server.vm.provision "shell", inline: <<-SHELL
            sudo echo "192.168.56.111 cmariotSW" >> /etc/hosts
            sudo apt-get update
            # TODO: Install k3s in controller mode
        SHELL
    end

    # Define the second VM: ServerWorker
    config.vm.define "cmariotSW" do |serverWorker|
        serverWorker.vm.box = "bento/ubuntu-24.04"
        serverWorker.vm.hostname = "cmariotSW"
        serverWorker.vm.network "private_network", ip: "192.168.56.111"
        serverWorker.vm.provider "virtualbox" do |vb|
            vb.cpus = 1
            vb.memory = "1024"
            # vb.gui = true
        end
        serverWorker.vm.provision "shell", inline: <<-SHELL
            sudo echo "192.168.56.110 wloS" >> /etc/hosts
            sudo apt-get update
            # TODO: Install k3s in agent mode
        SHELL
    end

end


# Check the IP address of the VMs
# vagrant ssh Server -c "ip a show eth1"
# ip addr show eth1


# Documentation :
# Vagrantfile : https://developer.hashicorp.com/vagrant/docs/vagrantfile
# Multi-Machine : https://developer.hashicorp.com/vagrant/docs/multi-machine
# Providers : https://developer.hashicorp.com/vagrant/docs/providers
# Machine Settings : https://developer.hashicorp.com/vagrant/docs/vagrantfile/machine_settings
# Private Networks : https://developer.hashicorp.com/vagrant/docs/networking/private_network
# SSH Settings : https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings
# Shell Provisioner : https://developer.hashicorp.com/vagrant/docs/provisioning/shell