BOX_IMAGE = "hashicorp/bionic64"
VM_PROVIDER = "virtualbox"

# Server
SERVER_NAME = "wloS"
SERVER_IP = "192.168.56.110"

# ServerWorker
SERVER_WORKER_NAME = "cmariotSW"
SERVER_WORKER_IP = "192.168.56.111"


Vagrant.configure("2") do |config|

    # Virtual machine provider settings
    config.vm.provider VM_PROVIDER do |vm_provider|
        vm_provider.cpus = 2
        vm_provider.memory = "1024"
        # vm_provider.gui = true
    end

    # Define the first VM: Server
    config.vm.define SERVER_NAME do |server|
        server.vm.box = BOX_IMAGE
        server.vm.hostname = SERVER_NAME
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.provision "shell", path: "scripts/server.sh"
    end

    # Define the second VM: ServerWorker
    config.vm.define SERVER_WORKER_NAME do |serverWorker|
        serverWorker.vm.box = BOX_IMAGE
        serverWorker.vm.hostname = SERVER_WORKER_NAME
        serverWorker.vm.network "private_network", ip: SERVER_WORKER_IP
        serverWorker.vm.provision "shell", path: "scripts/server_worker.sh"
    end

end


# SSH into the VMs
# vagrant ssh wloS
# vagrant ssh cmariotSW

# SSH into the VMs using the ssh-config file
# vagrant ssh-config wloS > ssh-config-wloS
# ssh -F ssh-config-wloS wloS

# Check the IP address of the VMs
# ip addr show eth1

# Check the status of the K3S cluster
# kubectl get nodes -o wide

# Server status :
# sudo systemctl status k3s

# ServerWorker status :
# sudo systemctl status k3s-agent


# Vagrant Documentation :
# Vagrantfile : https://developer.hashicorp.com/vagrant/docs/vagrantfile
# Multi-Machine : https://developer.hashicorp.com/vagrant/docs/multi-machine
# Providers : https://developer.hashicorp.com/vagrant/docs/providers
# Machine Settings : https://developer.hashicorp.com/vagrant/docs/vagrantfile/machine_settings
# Private Networks : https://developer.hashicorp.com/vagrant/docs/networking/private_network
# SSH Settings : https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings
# Shell Provisioner : https://developer.hashicorp.com/vagrant/docs/provisioning/shell

# K3S Documentation :
# https://docs.k3s.io/quick-start
# https://docs.k3s.io/installation/configuration