BOX_IMAGE = "bento/ubuntu-24.04"
VM_PROVIDER = "virtualbox"

# Server
SERVER_NAME = "wloS"
SERVER_IP = "192.168.56.110"


Vagrant.configure("2") do |config|

    # Virtual machine provider settings
    config.vm.provider VM_PROVIDER do |vm_provider|
        vm_provider.cpus = 4
        vm_provider.memory = "2048"
    end

    # Define the VM: Server
    config.vm.define SERVER_NAME do |server|
        server.vm.box = BOX_IMAGE
        server.vm.hostname = SERVER_NAME
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.provision "shell", path: "scripts/install.sh"
    end

end